// <auto-generated />
using System;
using MYGROCER.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MYGROCER.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617031437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MYGROCER.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MYGROCER.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MYGROCER.Models.ProductsModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BasePrice = 5.90m,
                            Category = "Fresh Produce",
                            Description = "Farm Fresh Full Cream Milk 1L",
                            ImageUrl = "https://www.farmfresh.com.my/wp-content/uploads/2021/10/FRESH-MILK-1L-UHT-SIDE-VIEW-768x768.png",
                            Name = "Farm Fresh Full Cream Milk ",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            BasePrice = 22.50m,
                            Category = "Packaged Goods",
                            Description = "Premium long grain basmati rice",
                            ImageUrl = "https://myweekendplan.asia/wp-content/uploads/2022/07/Cap-Keluarga-Maha-Basmathi-Rice-.jpg",
                            Name = "Maha Basmati Rice 5kg",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 3,
                            BasePrice = 18.90m,
                            Category = "Food & Beverages",
                            Description = "Chocolate malt UHT Packet Drink",
                            ImageUrl = "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13004616_XL1_20230622.jpg",
                            Name = "Milo Chocolate Malt",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 4,
                            BasePrice = 15.50m,
                            Category = "Home & Living",
                            Description = "Concentrated laundry powder",
                            ImageUrl = "https://tse1.mm.bing.net/th/id/OIP.iJZJOSkW_gY6Q19tMQMEFQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Ariel Downy Laundry Detergent 4KG",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 5,
                            BasePrice = 10.21m,
                            Category = "Fresh Produce",
                            Description = "Fresh boneless chicken breast",
                            ImageUrl = "https://media.naheed.pk/catalog/product/cache/ff36c7bc52e2e5dbc63cd67fba513679/m/e/me1173797-4.jpg",
                            Name = "Chicken Breast 1kg",
                            StockQuantity = 48
                        },
                        new
                        {
                            ProductId = 6,
                            BasePrice = 8.50m,
                            Category = "Food & Beverages",
                            Description = "100% pure squeezed orange juice",
                            ImageUrl = "https://aytacfood.co.uk/cdn/shop/products/sunquick-tropical-700ml-858288_1024x.jpg?v=1707828103",
                            Name = "Sunquick Tropical 700ml",
                            StockQuantity = 35
                        });
                });

            modelBuilder.Entity("MYGROCER.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "demo@mygrocer.local",
                            FullName = "Demo Customer",
                            Password = "password123",
                            Phone = "0123456789",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("MYGROCER.Models.OrderItem", b =>
                {
                    b.HasOne("MYGROCER.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MYGROCER.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
