// <auto-generated />
using MYGROCER.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MYGROCER.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MYGROCER.Models.ProductsModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BasePrice = 5.90m,
                            Category = "Fresh Produce",
                            Description = "Fresh full cream milk",
                            ImageUrl = "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=200",
                            Name = "Fresh Milk 1L",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            BasePrice = 22.50m,
                            Category = "Packaged Goods",
                            Description = "Premium long grain basmati rice",
                            ImageUrl = "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=200",
                            Name = "Basmati Rice 5kg",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 3,
                            BasePrice = 18.90m,
                            Category = "Food & Beverages",
                            Description = "Chocolate malt drink powder",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Milo_tin.jpg/200px-Milo_tin.jpg",
                            Name = "Milo 1kg",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 4,
                            BasePrice = 12.50m,
                            Category = "Home & Living",
                            Description = "Concentrated laundry powder",
                            ImageUrl = "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=200",
                            Name = "Washing Detergent 2kg",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 5,
                            BasePrice = 9.90m,
                            Category = "Fresh Produce",
                            Description = "Fresh boneless chicken breast",
                            ImageUrl = "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=200",
                            Name = "Chicken Breast 500g",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 6,
                            BasePrice = 8.50m,
                            Category = "Food & Beverages",
                            Description = "100% pure squeezed orange juice",
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=200",
                            Name = "Orange Juice 1L",
                            StockQuantity = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
